### ISSUE TITLE
Issue with adding virtual graphs using SMS

### ISSUE THREAD

**Issue by cgueret** [stardog-union/pystardog#62]
When trying to use `new_virtual_graph` to load a file wrote using SMS2 the uploader fails when validating the TTL file. 

```
Traceback (most recent call last):
  File "utils/configure_stardog.py", line 65, in <module>
    datasource=virtualgraph_name, db=config['stardog']['database'])
  File "/Users/christophe.gueret/opt/anaconda3/envs/Ampligraph/lib/python3.7/site-packages/stardog/admin.py", line 405, in new_virtual_graph
    self.client.post('/admin/virtual_graphs', json=meta)
  File "/Users/christophe.gueret/opt/anaconda3/envs/Ampligraph/lib/python3.7/site-packages/stardog/http/client.py", line 35, in post
    return self.__wrap(self.session.post(self.url + path, **kwargs))
  File "/Users/christophe.gueret/opt/anaconda3/envs/Ampligraph/lib/python3.7/site-packages/stardog/http/client.py", line 59, in __wrap
    'message', '')))
stardog.exceptions.StardogException: [400] QEIVR2: Expected ':', found '
' [L8]
```

**Comment by cgueret** [comment]
It seems passing on `options={'mappings.syntax': 'SMS2'}` works but I have then to add all the informations related to datasource to the options too as I otherwise get this error:
```
Traceback (most recent call last):
  File "utils/configure_stardog.py", line 66, in <module>
    datasource='Cohort-scoliosis', db=config['stardog']['database'],
  File "/Users/christophe.gueret/opt/anaconda3/envs/Ampligraph/lib/python3.7/site-packages/stardog/admin.py", line 405, in new_virtual_graph
    self.client.post('/admin/virtual_graphs', json=meta)
  File "/Users/christophe.gueret/opt/anaconda3/envs/Ampligraph/lib/python3.7/site-packages/stardog/http/client.py", line 35, in post
    return self.__wrap(self.session.post(self.url + path, **kwargs))
  File "/Users/christophe.gueret/opt/anaconda3/envs/Ampligraph/lib/python3.7/site-packages/stardog/http/client.py", line 59, in __wrap
    'message', '')))
stardog.exceptions.StardogException: [400] 000IA2: Unable to determine data source type. Expecting an option such as jdbc.url, mongodb.uri, cassandra.contact.point, elasticsearch.rest.urls or sparql.url.
```
So it seems `options` and `datasource` cannot be used at the same time

**Comment by snowell** [comment]
It does indeed seem like they cannot be used at the same time, but looking at the code it looks like it is done this way very much on purpose: https://github.com/stardog-union/pystardog/blob/47a707f94ce932617e1ed0f05fc315bdd3804a7f/stardog/admin.py#L546-L558
