### ISSUE TITLE
admin.virtual_graphs() returning objects where delete() 404s

### ISSUE THREAD

**Issue by snowell** [stardog-union/pystardog#77]
```python
>>> newvg = admin.new_virtual_graph('testing-vg', '', None, 'testing')
>>> shouldbesame = admin.virtual_graphs()[0]
>>> newvg
testing-vg
>>> shouldbesame
virtual://testing-vg
>>> shouldbesame.delete()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/stephen/.asdf/installs/python/3.9.6/lib/python3.9/site-packages/stardog/admin.py", line 1069, in delete
    self.client.delete(self.path)
  File "/Users/stephen/.asdf/installs/python/3.9.6/lib/python3.9/site-packages/stardog/http/client.py", line 44, in delete
    return self.__wrap(self.session.delete(self.url + path, **kwargs))
  File "/Users/stephen/.asdf/installs/python/3.9.6/lib/python3.9/site-packages/stardog/http/client.py", line 57, in __wrap
    raise exceptions.StardogException('[{}] {}: {}'.format(
stardog.exceptions.StardogException: [404] : Not Found!
>>> newvg.delete()
>>>
```

**Comment by scardena** [comment]
fixed here https://github.com/stardog-union/pystardog/pull/109
